version: '3'

services: 
    consumer:   
        build: .
        container_name: consumerComment
        restart: always
        volumes: 
            - ./productor&consumidor:/app
        command: >
            sh -c "python3 /app/consumerComment.py"
networks: 
  default:
    external: 
      name: app